### ISSUE TITLE
Publish Maven artifact

### ISSUE THREAD

**Issue by gaul** [gaul/java-httpbin#1]
And use this artifact from Chaos HTTP Proxy.

**Comment by gaul** [comment]
Published 1.0.0-SNAPSHOT; do not close until 1.0.0 released.

**Comment by gaul** [comment]
@snorp I integrated your changes and pushed a new snapshot; could you test if Firefox could use this jar instead of its fork before I publish 1.0.0?

**Comment by snorp** [comment]
I needed some other changes to make it work with Jetty 7.x (because 8.x and 9.x don't run on older Android), so probably not.
