### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by gaul** [gaul/java-httpbin#12]
master includes several new endpoints and fixes from the python httpbin tests.

@abeag Please test the latest 1.2.1-SNAPSHOT.  Report any issues then I can run a new release.

**Comment by abeag** [comment]
Done

**Comment by gaul** [comment]
Deployed 1.3.0 to Maven Central.  Thanks for your bug reports and testing!

**Comment by abeag** [comment]
Thanks and really appreciate the way you quickly resolved issues
